
CREATE TABLE doctor (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        lastName VARCHAR(255),
                        secondLastName VARCHAR(255),
                        specialty VARCHAR(255)
);


CREATE TABLE consultorio (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             numberConsultorio BIGINT,
                             piso INTEGER
);


CREATE TABLE cita (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      date DATE,
                      hora TIME,
                      namePacient VARCHAR(255),
                      doctorId BIGINT,
                      consultorioId BIGINT,
                      estado VARCHAR(255) NOT NULL,
                      FOREIGN KEY (doctorId) REFERENCES doctor(id),
                      FOREIGN KEY (consultorioId) REFERENCES consultorio(id)
);